// Small synthetic PrusaSlicer projects for the loader tests: a 3dmodel.model whose objects
// are tiny meshes (all triangles share three vertices), plus the Prusa metadata members.
import { zipAll } from "../../src/core";

const enc = new TextEncoder();

export interface ObjSpec {
  id: string;
  /** One entry per triangle: the mmu_segmentation string, or "" for an unpainted triangle. */
  paints: string[];
}

export interface VolSpec {
  first: number;
  last: number;
  type?: string;
  /** Written as the volume's extruder key when set (0 = explicit "inherit"). */
  extruder?: number;
  name?: string;
}

export interface ConfigObjSpec {
  id: string;
  name?: string;
  extruder?: number;
  volumes?: VolSpec[];
}

export const modelXml = (objects: ObjSpec[], items: string[] = objects.map((o) => o.id)): string =>
  `<?xml version="1.0"?><model unit="millimeter" xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02" xmlns:slic3rpe="http://schemas.slic3r.org/3mf/2017/06"><metadata name="Application">PrusaSlicer-2.9.6</metadata><resources>${objects.map((o) =>
    `<object id="${o.id}" type="model"><mesh><vertices><vertex x="0" y="0" z="0"/><vertex x="1" y="0" z="0"/><vertex x="0" y="1" z="0"/></vertices><triangles>${o.paints.map((p) =>
      `<triangle v1="0" v2="1" v3="2"${p ? ` slic3rpe:mmu_segmentation="${p}"` : ""}/>`).join("")}</triangles></mesh></object>`).join("")}</resources><build>${items.map((id) =>
    `<item objectid="${id}"/>`).join("")}</build></model>`;

/** Slic3r_PE_model.config in the layout PrusaSlicer 2.9 writes. */
export const modelConfig = (objects: ConfigObjSpec[]): string =>
  `<?xml version="1.0" encoding="UTF-8"?>\n<config>\n${objects.map((o) =>
    ` <object id="${o.id}" instances_count="1">\n${o.name !== undefined ? `  <metadata type="object" key="name" value="${o.name}"/>\n` : ""}${o.extruder !== undefined ? `  <metadata type="object" key="extruder" value="${o.extruder}"/>\n` : ""}${(o.volumes ?? []).map((v) =>
      `  <volume firstid="${v.first}" lastid="${v.last}">\n${v.name !== undefined ? `   <metadata type="volume" key="name" value="${v.name}"/>\n` : ""}${v.type !== undefined ? `   <metadata type="volume" key="volume_type" value="${v.type}"/>\n` : ""}${v.extruder !== undefined ? `   <metadata type="volume" key="extruder" value="${v.extruder}"/>\n` : ""}   <metadata type="volume" key="matrix" value="1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1"/>\n   <mesh edges_fixed="0" degenerate_facets="0" facets_removed="0" facets_reversed="0" backwards_edges="0"/>\n  </volume>\n`).join("")} </object>\n`).join("")}</config>\n`;

/** Slic3r_PE.config: only the lines the loader cares about, as `; key = value`. */
export const peConfig = (lines: Record<string, string>): string =>
  `; generated by PrusaSlicer 2.9.6 on 2026-07-10 at 08:50:37 UTC\n\n${Object.entries(lines).map(([k, v]) => `; ${k} = ${v}\n`).join("")}`;

export interface ArchiveSpec {
  objects: ObjSpec[];
  items?: string[];
  /** Extra archive members by name (text). */
  members?: Record<string, string>;
}

export async function archive(spec: ArchiveSpec): Promise<Uint8Array> {
  const files = [{ name: "3D/3dmodel.model", data: enc.encode(modelXml(spec.objects, spec.items)) }];
  for (const [name, text] of Object.entries(spec.members ?? {})) files.push({ name, data: enc.encode(text) });
  return zipAll(files);
}

export const PE_CONFIG = "Metadata/Slic3r_PE.config";
export const PE_MODEL = "Metadata/Slic3r_PE_model.config";
export const FULL_SPECTRUM = "Metadata/Prusa_Slicer_full_spectrum.json";
