// All user-facing text lives here so i18n can be added later (English only for now).
export const strings = {
  appName: "PaintPort+",
  header: {
    import: "Import",
    importHint: "Import a 3MF, STL or OBJ file",
    classic: "Classic",
    classicHint: "Open the original single-file PaintPort",
    undo: "Undo",
    undoHint: "Undo (Ctrl+Z)",
    redo: "Redo",
    redoHint: "Redo (Ctrl+Shift+Z)",
  },
  theme: {
    label: "Theme",
    light: "Light",
    dark: "Dark",
    system: "System",
  },
  tools: {
    label: "Tools",
    brush: "Brush",
    shellFill: "Shell fill",
    smartFill: "Smart fill",
    eraser: "Eraser",
    eyedropper: "Eyedropper",
  },
  viewport: {
    emptyTitle: "Drop a 3MF, STL or OBJ",
    emptyHint: "or use Import to pick a file",
    dropHint: "Drop to import",
    loading: "Reading file...",
    canvasLabel: "3D view of the model",
    viewerFailed: "The 3D view could not be shown. Your browser may not support WebGL, or the model is too large.",
    oneFileOnly: "Only one file is imported at a time. Imported the first one.",
    viewMode: "Viewport colors",
    design: "Design",
    print: "Print",
    printSoon: "The print preview comes with mapping and export in a later update.",
    eyedropperChip: "Color under the cursor",
  },
  panel: {
    paint: "Paint",
    objects: "Objects",
    export: "Export",
    palette: "Design palette",
    paletteEmpty: "Colors you paint with will appear here.",
    swatchLabel: "Design color",
    brush: "Brush",
    brushSize: "Brush size",
    radiusValue: (mm: string) => `${mm} mm`,
    paintThrough: "Paint through",
    paintThroughHint: "Also paint hidden and back-facing surface inside the brush.",
    smartFill: "Smart fill",
    smartFillAngle: "Edge angle",
    smartFillHint: "Smart fill stops at edges sharper than this.",
    angleValue: (degrees: number) => `${degrees}°`,
    objectsEmpty: "No objects loaded.",
    triangleCount: (n: number) => `${n.toLocaleString("en-US")} ${n === 1 ? "triangle" : "triangles"}`,
    unnamedObject: "Unnamed object",
    exportEmpty: "Mapping your colors to spools and exporting are coming in a later update.",
  },
  errors: {
    title: "Could not open file",
    dismiss: "Dismiss",
    generic: "The file could not be read.",
    // Keys are the stable `code`s of CoreError (src/core/errors.ts) and FormatError
    // (src/formats/errors.ts).
    codes: {
      ERR_NO_EOCD: "This is not a valid 3MF file (it is not a readable ZIP archive).",
      ERR_ZIP_CDIR: "The 3MF archive is damaged.",
      ERR_PAINT_SHORT: "The painting data in this file is incomplete.",
      ERR_PAINT_CHAR: "The painting data in this file is corrupt.",
      ERR_PAINT_TRAIL: "The painting data in this file is corrupt.",
      ERR_NO_MODEL: "This is not a valid 3MF file: the model part is missing.",
      ERR_MISSING_REF: "The 3MF refers to a part that is missing from the archive.",
      ERR_NO_OBJECTS: "The file contains no objects to print.",
      ERR_UNIT: "Only models in millimetres are supported.",
      ERR_BBS_NO_MIX: "Export is missing the ColorMix format.",
      ERR_BBS_MAX16: "Bambu Studio supports at most 16 filaments, including blends.",
      ERR_UNSUPPORTED_FORMAT: "Unsupported file type. Use a 3MF, STL or OBJ file.",
      ERR_STL_INVALID: "This is not a valid STL file.",
      ERR_STL_EMPTY: "The STL file contains no triangles.",
      ERR_OBJ_INVALID: "This is not a valid OBJ file.",
      ERR_OBJ_EMPTY: "The OBJ file contains no faces.",
    },
  },
} as const;
