// All user-facing text lives here so i18n can be added later (English only for now).
export const strings = {
  appName: "PaintPort+",
  header: {
    import: "Import",
    importHint: "Import a 3MF, STL or OBJ file",
    classic: "Classic",
    classicHint: "Open the original single-file PaintPort",
    undo: "Undo",
    undoHint: "Undo (Ctrl+Z)",
    redo: "Redo",
    redoHint: "Redo (Ctrl+Shift+Z)",
    newProject: "New",
    newProjectHint: "Start a new project",
  },
  settings: {
    label: "Settings",
  },
  theme: {
    label: "Theme",
    light: "Light",
    dark: "Dark",
    system: "System",
  },
  tools: {
    label: "Tools",
    brush: "Brush",
    shellFill: "Shell fill",
    smartFill: "Smart fill",
    eraser: "Eraser",
    eyedropper: "Eyedropper",
  },
  viewport: {
    emptyTitle: "Drop a 3MF, STL or OBJ",
    emptyHint: "or use Import to pick a file",
    dropHint: "Drop to import",
    loading: "Reading file...",
    canvasLabel: "3D view of the model",
    viewerFailed: "The 3D view could not be shown. Your browser may not support WebGL, or the model is too large.",
    oneFileOnly: "Only one file is imported at a time. Imported the first one.",
    sidecarIgnored: "This file has PaintPort+ design data, but it is damaged or doesn't match the model, so it was ignored. The colors come from the file's filaments instead.",
    viewMode: "Viewport colors",
    design: "Design",
    print: "Print",
    printHint: "Shows each color as it will print, using your spools.",
    printNote: "Print preview is view only. Switch to Design to paint.",
    toolsDisabled: "Tools are off in the Print view. Switch to Design to paint.",
    eyedropperChip: "Color under the cursor",
  },
  panel: {
    paint: "Paint",
    objects: "Objects",
    export: "Export",
    palette: "Design palette",
    paletteEmpty: "Colors you paint with will appear here.",
    brush: "Brush",
    brushSize: "Brush size",
    radiusValue: (mm: string) => `${mm} mm`,
    paintThrough: "Paint through",
    paintThroughHint: "Also paint hidden and back-facing surface inside the brush.",
    smartFill: "Smart fill",
    smartFillAngle: "Edge angle",
    smartFillHint: "Smart fill stops at edges sharper than this.",
    angleValue: (degrees: number) => `${degrees}°`,
    smartFillScale: "Feature size",
    smartFillScaleHint: "Ignores surface texture smaller than this. Off compares neighboring triangles.",
    scaleValue: (mm: number) => (mm > 0 ? `${mm.toFixed(2)} mm` : "Off"),
    objectsEmpty: "No objects loaded.",
    triangleCount: (n: number) => `${n.toLocaleString("en-US")} ${n === 1 ? "triangle" : "triangles"}`,
    unnamedObject: "Unnamed object",
    exportEmpty: "Open a model to map its colors to your spools and export it.",
  },
  palette: {
    swatch: (state: number, hex: string, unknown: boolean) => `Color ${state}, ${hex}${unknown ? ", unknown color" : ""}`,
    swatchTip: (state: number, hex: string) => `Color ${state} (${hex})`,
    colorName: (state: number) => `Color ${state}`,
    list: "Design colors",
    active: "Active color",
    unknown: "Unknown color",
    unknownHint: "The file didn't define this color, so PaintPort+ picked a stand-in. Edit it to set the real one.",
    add: "Add color",
    addTitle: "New color",
    addConfirm: "Add",
    cancel: "Cancel",
    edit: "Edit color",
    editTitle: (state: number) => `Edit color ${state}`,
    editHint: "Changes show on the model right away. Close to keep them.",
    done: "Done",
    picker: "Color picker",
    hex: "Hex color",
    hexInvalid: "Use 3 or 6 hex digits, like #1A2B3C.",
    delete: "Delete color",
    deleteLast: "The last color can't be deleted.",
    menuEdit: "Edit color...",
    menuDelete: "Delete color...",
    deleteTitle: (state: number) => `Delete color ${state}`,
    deleteDescription: "Everything painted with this color is merged into the color you choose below. You can undo this.",
    mergeInto: "Merge into",
    baseOption: "Base",
    baseOptionHint: "Back to each part's base color",
    baseUnavailable: (parts: number) =>
      `Not available: this is the base color of ${parts} ${parts === 1 ? "part" : "parts"}. Merge into another color and their base moves to it.`,
    usage: (painted: number, base: number) => {
      const n = (v: number) => v.toLocaleString("en-US");
      if (painted === 0 && base === 0) return "Not used on any surface";
      if (base === 0) return `${n(painted)} painted`;
      if (painted === 0) return `${n(base)} as base`;
      return `${n(painted)} painted, ${n(base)} as base`;
    },
    deleteConfirm: "Delete color",
  },
  objects: {
    list: "Objects",
    hide: (name: string) => `Hide ${name}`,
    show: (name: string) => `Show ${name}`,
    hiddenCount: (n: number) => `${n} hidden`,
    isolate: (name: string) => `Show only ${name}`,
    unisolate: "Show all objects again",
    showAll: "Show all",
    visibilityNote: "Hidden objects can't be painted and don't block the brush. This is only a view setting.",
    baseColor: "Base color",
    baseColorOf: (name: string) => `Base color of ${name}`,
    baseMixed: "Parts differ",
    baseMixedHint: "The parts of this object have different base colors. Choosing one sets them all.",
    chooseBase: "Choose a base color",
    noBase: "This object has no paintable part.",
    parts: (n: number) => `${n} parts`,
    expand: (name: string) => `Show the parts of ${name}`,
    collapse: (name: string) => `Hide the parts of ${name}`,
    unnamedPart: (n: number) => `Part ${n}`,
    modifier: "Modifier",
    modifierHint: "Modifiers aren't drawn or painted. Their color is applied when you export.",
  },
  export: {
    target: "Target slicer",
    targets: {
      prusa: "PrusaSlicer (Core One INDX)",
      bambu: "Bambu Studio",
      snapmaker: "Snapmaker Orca",
    },
    extruders: "Extruders",
    extrudersOption: (n: number) => `${n}`,
    spools: "Spools",
    spoolsHint: "Your printer's filaments. Design colors are matched to the spools that are on.",
    spoolOn: (slot: number) => `Use spool ${slot}`,
    spoolColor: (slot: number) => `Color of spool ${slot}`,
    spoolTitle: (slot: number) => `Spool ${slot} color`,
    spoolDone: "Done",
    moveUp: (slot: number) => `Move spool ${slot} up`,
    moveDown: (slot: number) => `Move spool ${slot} down`,
    presets: "Presets",
    presetName: (id: string) => (id === "PANCHROMA" ? "Panchroma" : id),
    presetTip: (id: string, count: number) => `Set spools 1 to ${count} to ${id === "PANCHROMA" ? "Polymaker Panchroma Translucent CMYK" : id}`,
    presetTruncated: (name: string, have: number, extruders: number) =>
      `${name} needs ${have} spools but the printer has ${extruders} extruders, so only the first ${extruders} were set.`,
    defaults: "Default colors",
    defaultsTitle: "Reset the spools?",
    defaultsDescription: "All spool colors and on/off settings go back to the defaults.",
    defaultsConfirm: "Reset spools",
    useFileSpools: "Use this file's spools",
    useFileSpoolsTip: "Set the spools to the filament colors stored in this file.",
    allowMix: "Allow ColorMix blends",
    allowMixHint: "Print a color as a blend of two or three spools when that matches it better.",
    mapping: "Color mapping",
    mappingHint: "Each color on the model is printed with a spool or a blend. Auto picks the closest match.",
    mappingEmpty: "No colors are used yet.",
    mappingRow: (state: number, hex: string) => `Color ${state}, ${hex}`,
    mappingSelect: (state: number) => `Print color ${state} as`,
    auto: "Auto",
    autoIs: (what: string) => `Auto: ${what}`,
    fromFile: (what: string) => `From file: ${what}`,
    pinned: "Pinned",
    noSpool: "no spool on",
    spoolName: (slot: number) => `Spool ${slot}`,
    dormantPin: (name: string) => `pinned ${name} is off`,
    blendParts: (ratio: number, slot: number) => `${ratio}×S${slot}`,
    groupSpools: "Spools",
    groupBlends: "Blends",
    deltaE: (d: number) => `ΔE ${d.toFixed(1)}`,
    resultOf: (color: string, deltaE: string) => `Prints as ${color}, ${deltaE}`,
    warnCollision: "These look different but print almost the same.",
    warnCollisionMore: (n: number) => `and ${n} more pairs`,
    warnPoorBlends: (n: number, free: number) =>
      `${n} ${n === 1 ? "color is" : "colors are"} blended poorly. ${free} extruder ${free === 1 ? "slot is" : "slots are"} free: turn on a spool that fits better.`,
    warnBambuLimit: (total: number) => `Bambu Studio allows 16 filaments including blends, and this needs ${total}. Turn off spools or use fewer blends.`,
    button: "Export 3MF",
    exporting: "Exporting...",
    noProject: "Open a model to export it.",
    noSpoolOn: "Turn on at least one spool to export.",
    exported: (fileName: string) => `Exported ${fileName}`,
    failed: "Export failed.",
    notReady: "Export is not available yet.",
  },
  session: {
    restoring: "Restoring your last session...",
    restored: "Restored your last session.",
    invalid:
      "Your last session couldn't be read. It is kept until you import a file or start a new project, which replaces it.",
    newer:
      "Your saved session was made by a newer version of PaintPort+ and can't be opened here. It has been left untouched; importing a file or starting a new project replaces it.",
    unavailable: "Autosave isn't available in this browser, so your work won't be restored after a reload.",
    otherTab: "PaintPort+ is open in another tab, so this tab won't autosave. Close the other tab and reload to work here.",
    conflict: "Another tab changed the saved project, so this tab stopped autosaving to avoid overwriting it. Reload to continue from the saved version.",
    stillRestoring: "Still restoring your last session. Try again in a moment.",
    autosaveFailed: "Autosave failed. Your browser may be out of storage space or blocking it, so recent changes could be lost if you reload.",
    clearFailed: "The autosaved copy couldn't be deleted, so it may come back after a reload.",
    newTitle: "Start a new project?",
    newDescription: "This closes the current project and deletes its autosaved copy. You can't undo this.",
    newNewerDescription: "This deletes the saved session from a newer version of PaintPort+. You can't undo this.",
    newUnreadableDescription: "This deletes the saved session that couldn't be read. You can't undo this.",
    newConfirm: "Start new project",
    replaceTitle: "Replace the saved session?",
    replaceDescription: "A session saved by a newer version of PaintPort+ is still stored. Importing this file replaces it.",
    replaceConfirm: "Replace and import",
    replaceOpenTitle: "Replace the open project?",
    replaceOpenDescription: "Importing this file replaces the project you are working on and its autosaved copy. You can't undo this.",
    cancel: "Cancel",
  },
  crash: {
    title: "Something went wrong",
    description: "PaintPort+ hit a problem and tried to save your work first. Try again to continue from your last autosave, or reload the page.",
    retry: "Try again",
    reload: "Reload page",
  },
  errors: {
    title: "Could not open file",
    dismiss: "Dismiss",
    generic: "The file could not be read.",
    // Keys are the stable `code`s of CoreError (src/core/errors.ts) and FormatError
    // (src/formats/errors.ts).
    codes: {
      ERR_NO_EOCD: "This is not a valid 3MF file (it is not a readable ZIP archive).",
      ERR_ZIP_CDIR: "The 3MF archive is damaged.",
      ERR_PAINT_SHORT: "The painting data in this file is incomplete.",
      ERR_PAINT_CHAR: "The painting data in this file is corrupt.",
      ERR_PAINT_TRAIL: "The painting data in this file is corrupt.",
      ERR_NO_MODEL: "This is not a valid 3MF file: the model part is missing.",
      ERR_MISSING_REF: "The 3MF refers to a part that is missing from the archive.",
      ERR_NO_OBJECTS: "The file contains no objects to print.",
      ERR_UNIT: "Only models in millimetres are supported.",
      ERR_BBS_NO_MIX: "Export is missing the ColorMix format.",
      ERR_BBS_MAX16: "Bambu Studio supports at most 16 filaments, including blends.",
      ERR_UNSUPPORTED_FORMAT: "Unsupported file type. Use a 3MF, STL or OBJ file.",
      ERR_STL_INVALID: "This is not a valid STL file.",
      ERR_STL_EMPTY: "The STL file contains no triangles.",
      ERR_OBJ_INVALID: "This is not a valid OBJ file.",
      ERR_OBJ_EMPTY: "The OBJ file contains no faces.",
      // Export refusals (DocError codes, src/doc/errors.ts).
      EXPORT_NO_SPOOL: "Turn on at least one spool before exporting.",
      EXPORT_UNMAPPED: "A color in the model could not be matched to a spool.",
      EXPORT_MIX_OFF: "A color needs a ColorMix blend, but ColorMix is off. Turn it on or pick a spool for that color.",
      EXPORT_BAMBU_LIMIT: "Bambu Studio supports at most 16 filaments, including blends. Turn off spools or pick fewer blends.",
      EXPORT_TOO_MANY: "This export needs more extruders than PrusaSlicer can paint. Pick fewer blends.",
    },
  },
} as const;
